
package com.sagar.jaxb.domain;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrders", targetNamespace = "http://www.sagar.com/jaxb")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrders {


    /**
     * 
     * @param id
     * @return
     *     returns com.sagar.jaxb.domain.PurchaseOrder
     */
    @WebMethod
    @WebResult(name = "order", targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.GetOrderResponse")
    @Action(input = "http://www.sagar.com/jaxb/PurchaseOrders/getOrderRequest", output = "http://www.sagar.com/jaxb/PurchaseOrders/getOrderResponse")
    public PurchaseOrder getOrder(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "removeOrder", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.RemoveOrder")
    @ResponseWrapper(localName = "removeOrderResponse", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.RemoveOrderResponse")
    @Action(input = "http://www.sagar.com/jaxb/PurchaseOrders/removeOrderRequest", output = "http://www.sagar.com/jaxb/PurchaseOrders/removeOrderResponse")
    public void removeOrder(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<com.sagar.jaxb.domain.PurchaseOrder>
     */
    @WebMethod
    @WebResult(name = "orders", targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.GetOrdersResponse")
    @Action(input = "http://www.sagar.com/jaxb/PurchaseOrders/getOrdersRequest", output = "http://www.sagar.com/jaxb/PurchaseOrders/getOrdersResponse")
    public List<PurchaseOrder> getOrders();

    /**
     * 
     * @param order
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://www.sagar.com/jaxb", className = "com.sagar.jaxb.domain.AddOrderResponse")
    @Action(input = "http://www.sagar.com/jaxb/PurchaseOrders/addOrderRequest", output = "http://www.sagar.com/jaxb/PurchaseOrders/addOrderResponse")
    public Long addOrder(
        @WebParam(name = "order", targetNamespace = "")
        PurchaseOrder order);

}
